version: 0.2
phases:
  install: 
    runtime-version:
      nodejs: 10
    commands: 
      - echo Getting started 
  pre_build: 
    commands: 
      - echo Installing some packages and source NPM dependecies...
      - npm install -g json
      - chmod +x ./build_scripts/create_configuraion.sh
      - sh /build_scripts/create_configuration.sh
      - npm install
      - aws --version

  build: 
    commands:
      - echo Build started on `date`
      - echo Run all of your build related code if any  
      - echo build finished, now moving S3

  post_build:
    commands:
      - echo Build complete on `date`


  artifacts:
    files:
      - '**/*'
